print('Hello, World!')
print('The books on the table.')
print('Mae! Sode No Shyirayuki!')
print('Bankai! Tensa Zangetsu!')
print('My job is very good, because my CEO is japanese.')
print('My favorite singer is TEMPOREX.')
print('Lol is disgusting game.')
print('My python teacher is calm.')
print('I like globgolgabgaleb.')
print('My favorite anime is One Piece, and my favorite caracter is Nico Robin!')